# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fish
canonical: http://example.org/fhir/fish
version: 0.0.1
name: SparkImplemenatationGuide
title: Spark Implemenatation Guide
status: draft
publisher: Paul Schneider
contact:
  - name: Paul Schneider
    telecom:
      - system: email
        value: paul.schneider@minfos.com.au
description: This is the Spark implementation guide
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2021+
releaseLabel: ci-build

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Background: background.html
  Downloads: downloads.html
  Artifacts Summary: artifacts.html
  Other Resources:
    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html
